<a href="https://colab.research.google.com/github/Raihan-009/FaceRecognition-opencv/blob/main/FaceRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World!")

Hello World!


**Loading Dataset**

In [2]:
from PIL import Image
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import zipfile
path = '/content/drive/MyDrive/Datasets for FR/yalefaces.zip'
zip_object = zipfile.ZipFile(file=path, mode='r')
zip_object.extractall('./')
zip_object.close()

**Data Pre-processing**

In [4]:
import os
print(os.listdir('/content/yalefaces/train'))

['subject04.happy.gif', 'subject04.sad.gif', 'subject13.glasses.gif', 'subject08.sleepy.gif', 'subject04.wink.gif', 'subject10.surprised.gif', 'subject06.noglasses.gif', 'subject04.centerlight.gif', 'subject04.sleepy.gif', 'subject05.leftlight.gif', 'subject11.normal.gif', 'subject15.glasses.gif', 'subject06.sad.gif', 'subject02.rightlight.gif', 'subject12.surprised.gif', 'subject02.happy.gif', 'subject10.noglasses.gif', 'subject14.surprised.gif', 'subject09.surprised.gif', 'subject03.happy.gif', 'subject07.surprised.gif', 'subject07.noglasses.gif', 'subject13.rightlight.gif', 'subject05.normal.gif', 'subject09.glasses.gif', 'subject15.sleepy.gif', 'subject01.leftlight.gif', 'subject12.happy.gif', 'subject07.sleepy.gif', 'subject08.wink.gif', 'subject13.leftlight.gif', 'subject14.glasses.gif', 'subject14.sleepy.gif', 'subject15.happy.gif', 'subject11.rightlight.gif', 'subject10.glasses.gif', 'subject01.rightlight.gif', 'subject06.wink.gif', 'subject01.glasses.gif', 'subject12.sad.gif',

In [5]:
def get_image_data():
  paths = [os.path.join('/content/yalefaces/train', f) for f in os.listdir('/content/yalefaces/train')]
  # print(paths)
  faces = []
  ids = []
  for path in paths:
    # print(path)
    image = Image.open(path).convert('L') ## converting into grayscale image
    # print(type(image))
    image_np = np.array(image, 'uint8')
    # print(type(image_np))
    id = int(os.path.split(path)[1].split('.')[0].replace('subject', ""))
    # print(id)
    ids.append(id)
    faces.append(image_np)

  return np.array(ids), faces


In [6]:
ids, faces = get_image_data()

In [7]:
ids

array([ 4,  4, 13,  8,  4, 10,  6,  4,  4,  5, 11, 15,  6,  2, 12,  2, 10,
       14,  9,  3,  7,  7, 13,  5,  9, 15,  1, 12,  7,  8, 13, 14, 14, 15,
       11, 10,  1,  6,  1, 12, 14,  5,  4,  6,  7, 12,  6, 10, 15,  3,  6,
       12,  8, 11,  5,  8,  2,  7, 13,  8, 14, 13,  9, 15,  9,  1, 12, 13,
        1,  1,  4,  5,  3,  4, 13,  7,  1,  5,  7, 11, 12,  3,  6,  8, 11,
        9, 15,  2,  9, 14,  4,  8, 10, 13,  9,  2, 15, 12, 10, 11,  1,  7,
       13,  7,  1, 10,  8,  3,  3,  5, 14,  6,  5,  3,  5, 15,  3, 15,  2,
       14,  6,  9,  2, 12, 10,  2, 10,  8, 11, 11,  2, 14,  9, 11,  3])

In [8]:
faces

[array([[130, 130, 130, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 252, 255, 255],
        [255, 255, 255, ..., 225, 236, 244],
        [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8),
 array([[130, 130, 130, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 251, 255, 255],
        [255, 255, 255, ..., 225, 236, 244],
        [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8),
 array([[130, 130, 130, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 201, 195, 199],
        [255, 255, 255, ..., 218, 211, 217],
        [ 68,  68,  68, ...,  68,  68,  68]], dtype=uint8),
 array([[130, 130, 130, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 25

In [9]:
len(ids)

135

In [10]:
len(faces)

135

In [11]:
faces[0].shape

(243, 320)

In [12]:
faces[5].shape

(243, 320)

In [13]:
faces[9].shape

(243, 320)

In [14]:
lbph_classifier = cv2.face.LBPHFaceRecognizer_create()
lbph_classifier.train(faces, ids)
lbph_classifier.write('lbph_classifier.yml')

**Recognizing Faces**

In [15]:
lbph_face_classifier = cv2.face.LBPHFaceRecognizer_create()
lbph_face_classifier.read('/content/lbph_classifier.yml')

In [16]:
test_image = '/content/yalefaces/test/subject03.glasses.gif'
image = Image.open(test_image).convert('L')
image_np = np.array(image, 'uint8')

In [17]:
prediction = lbph_face_classifier.predict(image_np)
prediction

(3, 13.081488574279117)

In [18]:
expected_output = int(os.path.split(test_image)[1].split('.')[0].replace('subject', ""))
expected_output

3